Quick fix for ERROR : <LOOP IN SUPERTYPES>
This commit fixes issue introduced with
logic for deserializeing super class relationships. Sometime
KotlinReflectionInternalError: Supertype not a class: [ERROR : <LOOP IN SUPERTYPES>]
error occures but we are not sure how to reproduce this issue